{
    'name': 'Electronic invoice KSA - POS | E- Invoice based on TLV Base64 string with Base 64 TLV QR Code',
    'version': '14.1.1.1',
    'summary': 'Saudi VAT E-Invoice for POS',
    'description': """Electronic invoice KSA - POS""",    
    'sequence': 1,
    'website':'www.odoobridge.com',
    'category': 'Point of Sale',
    "author" : "Odoobridge Solution",
    "email": 'support@odoobridge.com',
    'price': 15,
    'currency': 'EUR',
    'license': 'OPL-1',
    'depends': ['point_of_sale','l10n_gcc_pos','l10n_sa_pos'],
    'qweb': ['static/src/xml/templates.xml'],
    'data': ['views/pos_receipt_template.xml','views/product_view.xml'],
    "images": ['static/description/pos.gif'],
    "live_test_url" : "https://youtu.be/WC4UQ6F5Hq8",  
    'installable': True,
    'auto_install': False,
    'application': True,    
}
